name: 🎉 Grout.js - Release

on:
    release:
        types: [created]
    workflow_dispatch:

jobs:
    build:
        name: 🔨 Building
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [15.x]
        steps:
            - uses: actions/checkout@v2
            - name: Node.js ${{ matrix.node-version }}
            - uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: |
                git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
            - run: npm test
            - run: |
                npm run rm
                git add -A
                git commit -m "Remove dist" -a
            - run: npm run build
            - run: |
                git add -A
                git commit -m "Add dist" -a
            - name: Push changes
            uses: ad-m/github-push-action@master
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}